services:
  postgres:
    image: postgres:15
    container_name: careerflow-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sujith@2412
      POSTGRES_DB: careerflow
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: careerflow-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
